/**
 * Mad Libs voting public API.
 */
export {
  MAD_LIB_VOTES_COLLECTION,
  MAD_LIB_LOCKS_COLLECTION,
  MAD_LIB_ACTIVE_COLLECTION,
  buildVoteDocId,
  buildReservationVoterId,
  castVote,
  clearVoterIdentity,
  deleteAllMadLibVotes,
  deleteMadLibVote,
  fetchOwnVotes,
  getOrCreateAnonVoterId,
  loadVoterIdentity,
  saveAnonIdentity,
  saveReservationIdentity,
  setActiveMadLib,
  setMadLibLock,
  subscribeToActiveMadLib,
  subscribeToMadLibLock,
  subscribeToMadLibVotes,
  tallyVotes,
  type ActiveMadLibPointer,
  type FieldTally,
  type MadLibLock,
  type MadLibVote,
  type VoterIdentity,
} from './madLibsApi';
